// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oibjfhbkmpzieqqwlgrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pYmpmaGJrbXB6aWVxcXdsZ3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzI0OTUsImV4cCI6MjA2MjEwODQ5NX0.sXHcMoDPDfIBuf01mePnGOl097tRuMfW9Fbdk96RUMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);